{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "56357ff2-163d-4286-9efb-989fbb1628b6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "User vivek Registered Successfully!\n",
      "Merchant komal Registered Successfully!\n",
      "₹5000 added to wallet. Current Balance: ₹5000\n",
      "Wallet Balance: ₹5000\n",
      "Wallet Balance: ₹0\n",
      "₹1500 added to wallet. Current Balance: ₹1500\n",
      "Transaction of ₹1500 Successful from vivek to komal\n",
      "---- Transaction History ----\n",
      "2026-02-22 18:42:07.150664 | vivek sent ₹1500 to komal\n",
      "---- Transaction History ----\n",
      "2026-02-22 18:42:07.150664 | vivek sent ₹1500 to komal\n"
     ]
    }
   ],
   "source": [
    "\n",
    "from datetime import datetime\n",
    "\n",
    "# ---- Transaction Class ----\n",
    "class Transaction:\n",
    "    def __init__(self, sender, receiver, amount):\n",
    "        self.sender = sender\n",
    "        self.receiver = receiver\n",
    "        self.amount = amount\n",
    "        self.timestamp = datetime.now()\n",
    "\n",
    "    def display_transaction(self):\n",
    "        print(f\"{self.timestamp} | {self.sender} sent ₹{self.amount} to {self.receiver}\")\n",
    "\n",
    "# ---- Wallet Class ----\n",
    "class Wallet:\n",
    "    def __init__(self):\n",
    "        self.balance = 0\n",
    "        self.history = []\n",
    "\n",
    "    def add_money(self, amount):\n",
    "        self.balance += amount\n",
    "        print(f\"₹{amount} added to wallet. Current Balance: ₹{self.balance}\")\n",
    "\n",
    "    def deduct_money(self, amount):\n",
    "        if self.balance >= amount:\n",
    "            self.balance -= amount\n",
    "            return True\n",
    "        else:\n",
    "            print(\"Insufficient Wallet Balance!\")\n",
    "            return False\n",
    "\n",
    "    def show_balance(self):\n",
    "        print(f\"Wallet Balance: ₹{self.balance}\")\n",
    "\n",
    "    def add_transaction(self, transaction):\n",
    "        self.history.append(transaction)\n",
    "\n",
    "    def show_transaction_history(self):\n",
    "        print(\"---- Transaction History ----\")\n",
    "        for t in self.history:\n",
    "            t.display_transaction()\n",
    "\n",
    "# ---- User Class ----\n",
    "class User:\n",
    "    def __init__(self, name, phone, upi_pin):\n",
    "        self.name = name\n",
    "        self.phone = phone\n",
    "        self.__upi_pin = upi_pin\n",
    "        self.wallet = Wallet()\n",
    "\n",
    "    def verify_pin(self, pin):\n",
    "        return self.__upi_pin == pin\n",
    "\n",
    "# ---- Merchant Class ----\n",
    "class Merchant(User):\n",
    "    def __init__(self, name, phone, upi_pin, shop_name):\n",
    "        super().__init__(name, phone, upi_pin)\n",
    "        self.shop_name = shop_name\n",
    "\n",
    "# ---- GPay System Class ----\n",
    "class GPaySystem:\n",
    "    def __init__(self):\n",
    "        self.users = {}\n",
    "\n",
    "    def register_user(self, name, phone, upi_pin):\n",
    "        if phone in self.users:\n",
    "            print(\"User already registered!\")\n",
    "        else:\n",
    "            self.users[phone] = User(name, phone, upi_pin)\n",
    "            print(f\"User {name} Registered Successfully!\")\n",
    "\n",
    "    def register_merchant(self, name, phone, upi_pin, shop_name):\n",
    "        if phone in self.users:\n",
    "            print(\"Merchant already registered!\")\n",
    "        else:\n",
    "            self.users[phone] = Merchant(name, phone, upi_pin, shop_name)\n",
    "            print(f\"Merchant {name} Registered Successfully!\")\n",
    "\n",
    "    def send_money(self, sender_phone, receiver_phone, amount, pin):\n",
    "        sender = self.users.get(sender_phone)\n",
    "        receiver = self.users.get(receiver_phone)\n",
    "\n",
    "        if not sender or not receiver:\n",
    "            print(\"Invalid Sender or Receiver!\")\n",
    "            return\n",
    "\n",
    "        if not sender.verify_pin(pin):\n",
    "            print(\"Invalid UPI PIN. Transaction Failed!\")\n",
    "            return\n",
    "\n",
    "        if sender.wallet.deduct_money(amount):\n",
    "            receiver.wallet.add_money(amount)\n",
    "            transaction = Transaction(sender.name, receiver.name, amount)\n",
    "            sender.wallet.add_transaction(transaction)\n",
    "            receiver.wallet.add_transaction(transaction)\n",
    "            print(f\"Transaction of ₹{amount} Successful from {sender.name} to {receiver.name}\")\n",
    "\n",
    "    def show_user_balance(self, phone):\n",
    "        user = self.users.get(phone)\n",
    "        if user:\n",
    "            user.wallet.show_balance()\n",
    "        else:\n",
    "            print(\"User not found!\")\n",
    "\n",
    "    def show_transaction_history(self, phone):\n",
    "        user = self.users.get(phone)\n",
    "        if user:\n",
    "            user.wallet.show_transaction_history()\n",
    "        else:\n",
    "            print(\"User not found!\")\n",
    "\n",
    "gpay = GPaySystem()\n",
    "\n",
    "gpay.register_user(\"vivek\", \"9876543210\", \"1234\")\n",
    "gpay.register_merchant(\"komal\", \"9999999999\", \"5678\", \"komal Electronics\")\n",
    "\n",
    "\n",
    "gpay.users[\"9876543210\"].wallet.add_money(5000)\n",
    "\n",
    "gpay.show_user_balance(\"9876543210\")\n",
    "gpay.show_user_balance(\"9999999999\")\n",
    "\n",
    "gpay.send_money(\"9876543210\", \"9999999999\", 1500, \"1234\")\n",
    "\n",
    "gpay.show_transaction_history(\"9876543210\")\n",
    "gpay.show_transaction_history(\"9999999999\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
